-- begin TESTAPP_SCHEDULE
alter table TESTAPP_SCHEDULE add constraint FK_TESTAPP_SCHEDULE_ON_TEACHER foreign key (TEACHER_ID) references TESTAPP_TEACHER(ID)^
alter table TESTAPP_SCHEDULE add constraint FK_TESTAPP_SCHEDULE_ON_SUBJECT foreign key (SUBJECT_ID) references TESTAPP_SUBJECT(ID)^
create index IDX_TESTAPP_SCHEDULE_ON_TEACHER on TESTAPP_SCHEDULE (TEACHER_ID)^
create index IDX_TESTAPP_SCHEDULE_ON_SUBJECT on TESTAPP_SCHEDULE (SUBJECT_ID)^
-- end TESTAPP_SCHEDULE
-- begin TESTAPP_SCHEDULE_STUDENT_LINK
alter table TESTAPP_SCHEDULE_STUDENT_LINK add constraint FK_SCHSTU_ON_SCHEDULE foreign key (SCHEDULE_ID) references TESTAPP_SCHEDULE(ID)^
alter table TESTAPP_SCHEDULE_STUDENT_LINK add constraint FK_SCHSTU_ON_STUDENT foreign key (STUDENT_ID) references TESTAPP_STUDENT(ID)^
-- end TESTAPP_SCHEDULE_STUDENT_LINK
