alter table TESTAPP_SCHEDULE add constraint FK_TESTAPP_SCHEDULE_ON_TEACHER foreign key (TEACHER_ID) references TESTAPP_TEACHER(ID);
alter table TESTAPP_SCHEDULE add constraint FK_TESTAPP_SCHEDULE_ON_SUBJECT foreign key (SUBJECT_ID) references TESTAPP_SUBJECT(ID);
create index IDX_TESTAPP_SCHEDULE_ON_TEACHER on TESTAPP_SCHEDULE (TEACHER_ID);
create index IDX_TESTAPP_SCHEDULE_ON_SUBJECT on TESTAPP_SCHEDULE (SUBJECT_ID);
