alter table TESTAPP_SCHEDULE add constraint FK_TESTAPP_SCHEDULE_ON_STUDENT foreign key (STUDENT_ID) references TESTAPP_STUDENT(ID);
create index IDX_TESTAPP_SCHEDULE_ON_STUDENT on TESTAPP_SCHEDULE (STUDENT_ID);
